services:
  frontend:
    image: bankinfra_frontend:1.0.0-alpha.1
    ports:
      - "3001:3001"
    working_dir: /app
  backend:
    image: bankinfra_backend:1.0.0-alpha.1
    ports:
      - "5000:5000"
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=$$MYSQL_ROOT_PASSWORD", "--host=127.0.0.1", "--execute", "SELECT 1;"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data: